@startuml

class Game {
    - width: int
    - height: int
    - grid_size: int
    - tile_size: int
    - white: tuple
    - whiteblock: Image
    - screen: Surface
    - font: Font
    - IMAGE_PATH: str
    - TIME_LIMIT: int
    - tiles: list
    - selected_index: int
    - clock: Clock
    - start_ticks: int
    - dragging: bool
    - drag_tile_index: int
    - dragged_tile_image: Image
    - old_tile_image: Image
    - old_tile_image_index: int

    + load_image(path: str): list
    + shuffle_tiles(): None
    + draw_tiles(): None
    + swap_tiles(index1: int, index2: int): None
    + draw_text(text: str, position: tuple): None
    + check_win(right_image: list): bool
    + view_original_image(): None
    + game_loop(): None
}

class Menu {
    - root: Tk
    - GAME_IMAGE_PATH: str
    - GAME_GRID: int
    - GAME_TIME: int
    - frame: Frame
    - time_entry: Entry
    - segment_entry: Entry

    + select_image(): None
    + exit_program(): None
}

Menu --> Game : "启动游戏时使用"

@enduml
